repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: [--pytest]
      - id: pretty-format-json
        args: [--autofix]
      - id: check-added-large-files
        args: [--maxkb=1500]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --target-version=py310
          - --line-length=120
          - --exclude=\.git|\.hg|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist
          - --include=\.pyi?$
          - --diff

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=122
          - --extend-ignore=E203,W503

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=120
